spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: tiger
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
